# -*- coding: utf-8 -*-
"""AI text-to-image generator

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fN39TJzA3cXKr47VoI8nSoN8Tr-owD0o
"""

!pip install diffusers transformers accelerate --upgrade
!pip install safetensors

import torch
from diffusers import StableDiffusionPipeline
import matplotlib.pyplot as plt

from huggingface_hub import login
login("your hugging face access token")

pipe = StableDiffusionPipeline.from_pretrained(
    "runwayml/stable-diffusion-v1-5",
    torch_dtype=torch.float16,
    use_safetensors=True
)
pipe = pipe.to("cuda")

user_promt = input("Enter your image promt: ")

image = pipe(user_promt).images[0]


# Display the generated image
plt.imshow(image)
plt.axis("off")
plt.title("Generated Image")
plt.show()